### ISSUE TITLE
Function sometimes return wrong values

### ISSUE THREAD

**Issue by 109C** [bobbybee/scratch-llvm#1]
the following code always prints "1 is equal to 2". I'm not entirely sure why, however when I change the return value code of @CallReturn from

[set [return value] to (item (sp + 1) of [DATA])]
to
[set [return value] to (item (sp + 0) of [DATA])]

it returns the correct value.

```
int main(){
  if(CallReturn(1) == CallReturn(2)){
    puts("1 is equal to 2");
  }else{
    puts("1 is not equal to 2");
  }
}
}
int CallReturn(int number){
  return(number);
}
```

**Comment by bobbybee** [comment]
I'll look into it.

**Comment by bobbybee** [comment]
Ooo, interesting. The bug seems to be due to the stack pointer being adjusted _before_ the return value is set, thus pointing to an incorrect value of the return pointer relative to the stack. Writing a patch shouldn't be too difficult..

**Comment by bobbybee** [comment]
Try now :)

**Comment by 109C** [comment]
Yes, I tried it and it seems to be fixed. Thanks!

**Comment by bobbybee** [comment]
@109C No problem :) Thanks for the bug report! BTW, what's your username on Scratch? 109C?
